version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: fima-postgres
    environment:
      POSTGRES_DB: fima
      POSTGRES_USER: fima
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fima-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: fima
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - '5672:5672'
      - '15672:15672'

  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-20T10-10-10Z
    container_name: fima-minio
    environment:
      MINIO_ROOT_USER: fima
      MINIO_ROOT_PASSWORD: secret123
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data

volumes:
  pgdata:
  minio:
